env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  # Both these are no longer needed: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"
